### ISSUE TITLE
.NET 4.5.2 on Windows 2012 R2 does not install correctly

### ISSUE THREAD

**Issue by kerbou** [puppet-community/puppet-dotnet#13]
I am experiencing an error trying to install .NET 4.5.2 on Windows 2012 R2 - the reason is that the registry key 

*HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{26784146-6E05-3FF9-9335-786C7C0FB5BE}*

does not exist so powershell exits with a 1 instead of 0

For information, see https://msdn.microsoft.com/en-us/library/hh925568(v=vs.110).aspx - a solution could be to to check the OS-version and change registry lookup accordingly

**Comment by liamjbennett** [comment]
Fixed in 1.0.2 by #11
